/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecruteursRouteImport } from './routes/recruteurs'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as OpportunitesRouteImport } from './routes/opportunites'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MesCandidaturesRouteImport } from './routes/mes-candidatures'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EvenementsRouteImport } from './routes/evenements'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as BonsPlansRouteImport } from './routes/bons-plans'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FounderSuccessRouteImport } from './routes/founder.success'
import { Route as DashboardRecruteurRouteImport } from './routes/dashboard/recruteur'
import { Route as DashboardLyceenRouteImport } from './routes/dashboard/lyceen'
import { Route as DashboardEtudiantRouteImport } from './routes/dashboard/etudiant'
import { Route as DashboardEcoleRouteImport } from './routes/dashboard/ecole'
import { Route as DashboardDiplomeRouteImport } from './routes/dashboard/diplome'
import { Route as AdminBonsPlansRouteImport } from './routes/admin/bons-plans'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruteursRoute = RecruteursRouteImport.update({
  id: '/recruteurs',
  path: '/recruteurs',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitesRoute = OpportunitesRouteImport.update({
  id: '/opportunites',
  path: '/opportunites',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MesCandidaturesRoute = MesCandidaturesRouteImport.update({
  id: '/mes-candidatures',
  path: '/mes-candidatures',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsRoute = EvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const BonsPlansRoute = BonsPlansRouteImport.update({
  id: '/bons-plans',
  path: '/bons-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderSuccessRoute = FounderSuccessRouteImport.update({
  id: '/founder/success',
  path: '/founder/success',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRecruteurRoute = DashboardRecruteurRouteImport.update({
  id: '/dashboard/recruteur',
  path: '/dashboard/recruteur',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLyceenRoute = DashboardLyceenRouteImport.update({
  id: '/dashboard/lyceen',
  path: '/dashboard/lyceen',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEtudiantRoute = DashboardEtudiantRouteImport.update({
  id: '/dashboard/etudiant',
  path: '/dashboard/etudiant',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEcoleRoute = DashboardEcoleRouteImport.update({
  id: '/dashboard/ecole',
  path: '/dashboard/ecole',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDiplomeRoute = DashboardDiplomeRouteImport.update({
  id: '/dashboard/diplome',
  path: '/dashboard/diplome',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBonsPlansRoute = AdminBonsPlansRouteImport.update({
  id: '/admin/bons-plans',
  path: '/admin/bons-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bons-plans': typeof BonsPlansRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/evenements': typeof EvenementsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mentors': typeof MentorsRoute
  '/mes-candidatures': typeof MesCandidaturesRoute
  '/messages': typeof MessagesRoute
  '/opportunites': typeof OpportunitesRoute
  '/profil': typeof ProfilRoute
  '/recherche': typeof RechercheRoute
  '/recruteurs': typeof RecruteursRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin/bons-plans': typeof AdminBonsPlansRoute
  '/dashboard/diplome': typeof DashboardDiplomeRoute
  '/dashboard/ecole': typeof DashboardEcoleRoute
  '/dashboard/etudiant': typeof DashboardEtudiantRoute
  '/dashboard/lyceen': typeof DashboardLyceenRoute
  '/dashboard/recruteur': typeof DashboardRecruteurRoute
  '/founder/success': typeof FounderSuccessRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bons-plans': typeof BonsPlansRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/evenements': typeof EvenementsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mentors': typeof MentorsRoute
  '/mes-candidatures': typeof MesCandidaturesRoute
  '/messages': typeof MessagesRoute
  '/opportunites': typeof OpportunitesRoute
  '/profil': typeof ProfilRoute
  '/recherche': typeof RechercheRoute
  '/recruteurs': typeof RecruteursRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin/bons-plans': typeof AdminBonsPlansRoute
  '/dashboard/diplome': typeof DashboardDiplomeRoute
  '/dashboard/ecole': typeof DashboardEcoleRoute
  '/dashboard/etudiant': typeof DashboardEtudiantRoute
  '/dashboard/lyceen': typeof DashboardLyceenRoute
  '/dashboard/recruteur': typeof DashboardRecruteurRoute
  '/founder/success': typeof FounderSuccessRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/bons-plans': typeof BonsPlansRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/evenements': typeof EvenementsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mentors': typeof MentorsRoute
  '/mes-candidatures': typeof MesCandidaturesRoute
  '/messages': typeof MessagesRoute
  '/opportunites': typeof OpportunitesRoute
  '/profil': typeof ProfilRoute
  '/recherche': typeof RechercheRoute
  '/recruteurs': typeof RecruteursRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/admin/bons-plans': typeof AdminBonsPlansRoute
  '/dashboard/diplome': typeof DashboardDiplomeRoute
  '/dashboard/ecole': typeof DashboardEcoleRoute
  '/dashboard/etudiant': typeof DashboardEtudiantRoute
  '/dashboard/lyceen': typeof DashboardLyceenRoute
  '/dashboard/recruteur': typeof DashboardRecruteurRoute
  '/founder/success': typeof FounderSuccessRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bons-plans'
    | '/cgu'
    | '/confidentialite'
    | '/evenements'
    | '/forgot-password'
    | '/login'
    | '/mentions-legales'
    | '/mentors'
    | '/mes-candidatures'
    | '/messages'
    | '/opportunites'
    | '/profil'
    | '/recherche'
    | '/recruteurs'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/admin/bons-plans'
    | '/dashboard/diplome'
    | '/dashboard/ecole'
    | '/dashboard/etudiant'
    | '/dashboard/lyceen'
    | '/dashboard/recruteur'
    | '/founder/success'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bons-plans'
    | '/cgu'
    | '/confidentialite'
    | '/evenements'
    | '/forgot-password'
    | '/login'
    | '/mentions-legales'
    | '/mentors'
    | '/mes-candidatures'
    | '/messages'
    | '/opportunites'
    | '/profil'
    | '/recherche'
    | '/recruteurs'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/admin/bons-plans'
    | '/dashboard/diplome'
    | '/dashboard/ecole'
    | '/dashboard/etudiant'
    | '/dashboard/lyceen'
    | '/dashboard/recruteur'
    | '/founder/success'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/bons-plans'
    | '/cgu'
    | '/confidentialite'
    | '/evenements'
    | '/forgot-password'
    | '/login'
    | '/mentions-legales'
    | '/mentors'
    | '/mes-candidatures'
    | '/messages'
    | '/opportunites'
    | '/profil'
    | '/recherche'
    | '/recruteurs'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/admin'
    | '/admin/bons-plans'
    | '/dashboard/diplome'
    | '/dashboard/ecole'
    | '/dashboard/etudiant'
    | '/dashboard/lyceen'
    | '/dashboard/recruteur'
    | '/founder/success'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BonsPlansRoute: typeof BonsPlansRoute
  CguRoute: typeof CguRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  EvenementsRoute: typeof EvenementsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MentorsRoute: typeof MentorsRoute
  MesCandidaturesRoute: typeof MesCandidaturesRoute
  MessagesRoute: typeof MessagesRoute
  OpportunitesRoute: typeof OpportunitesRoute
  ProfilRoute: typeof ProfilRoute
  RechercheRoute: typeof RechercheRoute
  RecruteursRoute: typeof RecruteursRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AdminBonsPlansRoute: typeof AdminBonsPlansRoute
  DashboardDiplomeRoute: typeof DashboardDiplomeRoute
  DashboardEcoleRoute: typeof DashboardEcoleRoute
  DashboardEtudiantRoute: typeof DashboardEtudiantRoute
  DashboardLyceenRoute: typeof DashboardLyceenRoute
  DashboardRecruteurRoute: typeof DashboardRecruteurRoute
  FounderSuccessRoute: typeof FounderSuccessRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruteurs': {
      id: '/recruteurs'
      path: '/recruteurs'
      fullPath: '/recruteurs'
      preLoaderRoute: typeof RecruteursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunites': {
      id: '/opportunites'
      path: '/opportunites'
      fullPath: '/opportunites'
      preLoaderRoute: typeof OpportunitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes-candidatures': {
      id: '/mes-candidatures'
      path: '/mes-candidatures'
      fullPath: '/mes-candidatures'
      preLoaderRoute: typeof MesCandidaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements': {
      id: '/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof EvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bons-plans': {
      id: '/bons-plans'
      path: '/bons-plans'
      fullPath: '/bons-plans'
      preLoaderRoute: typeof BonsPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/success': {
      id: '/founder/success'
      path: '/founder/success'
      fullPath: '/founder/success'
      preLoaderRoute: typeof FounderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/recruteur': {
      id: '/dashboard/recruteur'
      path: '/dashboard/recruteur'
      fullPath: '/dashboard/recruteur'
      preLoaderRoute: typeof DashboardRecruteurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/lyceen': {
      id: '/dashboard/lyceen'
      path: '/dashboard/lyceen'
      fullPath: '/dashboard/lyceen'
      preLoaderRoute: typeof DashboardLyceenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/etudiant': {
      id: '/dashboard/etudiant'
      path: '/dashboard/etudiant'
      fullPath: '/dashboard/etudiant'
      preLoaderRoute: typeof DashboardEtudiantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/ecole': {
      id: '/dashboard/ecole'
      path: '/dashboard/ecole'
      fullPath: '/dashboard/ecole'
      preLoaderRoute: typeof DashboardEcoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/diplome': {
      id: '/dashboard/diplome'
      path: '/dashboard/diplome'
      fullPath: '/dashboard/diplome'
      preLoaderRoute: typeof DashboardDiplomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bons-plans': {
      id: '/admin/bons-plans'
      path: '/admin/bons-plans'
      fullPath: '/admin/bons-plans'
      preLoaderRoute: typeof AdminBonsPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BonsPlansRoute: BonsPlansRoute,
  CguRoute: CguRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  EvenementsRoute: EvenementsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MentorsRoute: MentorsRoute,
  MesCandidaturesRoute: MesCandidaturesRoute,
  MessagesRoute: MessagesRoute,
  OpportunitesRoute: OpportunitesRoute,
  ProfilRoute: ProfilRoute,
  RechercheRoute: RechercheRoute,
  RecruteursRoute: RecruteursRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AdminBonsPlansRoute: AdminBonsPlansRoute,
  DashboardDiplomeRoute: DashboardDiplomeRoute,
  DashboardEcoleRoute: DashboardEcoleRoute,
  DashboardEtudiantRoute: DashboardEtudiantRoute,
  DashboardLyceenRoute: DashboardLyceenRoute,
  DashboardRecruteurRoute: DashboardRecruteurRoute,
  FounderSuccessRoute: FounderSuccessRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
