/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RecruteursRouteImport } from './routes/recruteurs'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as OpportunitesRouteImport } from './routes/opportunites'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EvenementsRouteImport } from './routes/evenements'
import { Route as BonsPlansRouteImport } from './routes/bons-plans'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FounderSuccessRouteImport } from './routes/founder.success'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruteursRoute = RecruteursRouteImport.update({
  id: '/recruteurs',
  path: '/recruteurs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitesRoute = OpportunitesRouteImport.update({
  id: '/opportunites',
  path: '/opportunites',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsRoute = EvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const BonsPlansRoute = BonsPlansRouteImport.update({
  id: '/bons-plans',
  path: '/bons-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderSuccessRoute = FounderSuccessRouteImport.update({
  id: '/founder/success',
  path: '/founder/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bons-plans': typeof BonsPlansRoute
  '/evenements': typeof EvenementsRoute
  '/login': typeof LoginRoute
  '/mentors': typeof MentorsRoute
  '/opportunites': typeof OpportunitesRoute
  '/profil': typeof ProfilRoute
  '/recruteurs': typeof RecruteursRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/founder/success': typeof FounderSuccessRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bons-plans': typeof BonsPlansRoute
  '/evenements': typeof EvenementsRoute
  '/login': typeof LoginRoute
  '/mentors': typeof MentorsRoute
  '/opportunites': typeof OpportunitesRoute
  '/profil': typeof ProfilRoute
  '/recruteurs': typeof RecruteursRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/founder/success': typeof FounderSuccessRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/bons-plans': typeof BonsPlansRoute
  '/evenements': typeof EvenementsRoute
  '/login': typeof LoginRoute
  '/mentors': typeof MentorsRoute
  '/opportunites': typeof OpportunitesRoute
  '/profil': typeof ProfilRoute
  '/recruteurs': typeof RecruteursRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/founder/success': typeof FounderSuccessRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bons-plans'
    | '/evenements'
    | '/login'
    | '/mentors'
    | '/opportunites'
    | '/profil'
    | '/recruteurs'
    | '/signup'
    | '/admin'
    | '/founder/success'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bons-plans'
    | '/evenements'
    | '/login'
    | '/mentors'
    | '/opportunites'
    | '/profil'
    | '/recruteurs'
    | '/signup'
    | '/admin'
    | '/founder/success'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/bons-plans'
    | '/evenements'
    | '/login'
    | '/mentors'
    | '/opportunites'
    | '/profil'
    | '/recruteurs'
    | '/signup'
    | '/_authenticated/admin'
    | '/founder/success'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BonsPlansRoute: typeof BonsPlansRoute
  EvenementsRoute: typeof EvenementsRoute
  LoginRoute: typeof LoginRoute
  MentorsRoute: typeof MentorsRoute
  OpportunitesRoute: typeof OpportunitesRoute
  ProfilRoute: typeof ProfilRoute
  RecruteursRoute: typeof RecruteursRoute
  SignupRoute: typeof SignupRoute
  FounderSuccessRoute: typeof FounderSuccessRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruteurs': {
      id: '/recruteurs'
      path: '/recruteurs'
      fullPath: '/recruteurs'
      preLoaderRoute: typeof RecruteursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunites': {
      id: '/opportunites'
      path: '/opportunites'
      fullPath: '/opportunites'
      preLoaderRoute: typeof OpportunitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements': {
      id: '/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof EvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bons-plans': {
      id: '/bons-plans'
      path: '/bons-plans'
      fullPath: '/bons-plans'
      preLoaderRoute: typeof BonsPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/success': {
      id: '/founder/success'
      path: '/founder/success'
      fullPath: '/founder/success'
      preLoaderRoute: typeof FounderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BonsPlansRoute: BonsPlansRoute,
  EvenementsRoute: EvenementsRoute,
  LoginRoute: LoginRoute,
  MentorsRoute: MentorsRoute,
  OpportunitesRoute: OpportunitesRoute,
  ProfilRoute: ProfilRoute,
  RecruteursRoute: RecruteursRoute,
  SignupRoute: SignupRoute,
  FounderSuccessRoute: FounderSuccessRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
